name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Move PDFs
        run: mv ./*.pdf dist
        shell: bash

      - name: Move index page
        run: cp README.md dist/index.md
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: dist
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: true
